script: git checkout develop && make test-app-ci
deploy:
  provider: heroku
  api_key:
    secure: R0ZDglJ0XlMk9skwPqDmnBhTDHHxvH15qJ5d/K3u/stte7DPSs+ZBKaxXoJrFb8yXMD4AXhmMAS5XpvVw8P9y9rbJ2Jg/6VLdVqTCnlwMgwbFCa28s9YKXjJiGCjb2XDVDUvBfDqAjLxBxogPZd/E2hoNnMeWJcSnpTuHsFW9xg=
  app:
    develop: filmster-core-func01
